version: '3'

services:
  web:
    build: .
    ports:
    - "8080:3333"
    volumes:
    - .:/app
    working_dir: /app
    command: "npm run dev"

#   adonis-mysql:
#     image: 13.1-alpine
#     ports:
#       - '3307:3306'
#     volumes:
#       - $PWD/data:/var/lib/mysql
#     environment:
#       MYSQL_USER: ${DB_USER}
#       MYSQL_DATABASE: ${DB_DATABASE}
#       MYSQL_PASSWORD: ${DB_PASSWORD}
#       MYSQL_ALLOW_EMPTY_PASSWORD: ${DB_ALLOW_EMPTY_PASSWORD}
#     networks:
#       - api-network
#   adonis-api:
#     container_name: "${APP_NAME}-api"
#     build:
#       context: .
#       dockerfile: Dockerfile
#     volumes:
#       - .:/app
#       - /app/node_modules
#     ports:
#       - "3333:3333"
#     depends_on:
#       - adonis-mysql
#     networks:
#       - api-network

# networks:
#   api-network:
